services:
  - type: web
    name: hospital-backend-1307
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: FRONTEND_URL
        value: https://hospital-frontend-1307.onrender.com
      - key: BETTER_AUTH_URL
        value: https://hospital-backend-1307.onrender.com
      - key: MONGO_URI
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: GEMINI_KEY
        sync: false
      - key: UPLOADTHING_TOKEN
        sync: false
      - key: POLAR_PRODUCT_ID
        sync: false
      - key: POLAR_ACCESS_TOKEN
        sync: false
      - key: POLAR_WEBHOOK_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        value: nan539806@gmail.com
      - key: SMTP_PASS
        sync: false

  - type: web
    name: hospital-frontend-1307
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_BACKEND_URL
        value: https://hospital-backend-1307.onrender.com
